//Categories types
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_FILTERS = "GET_ALL_CATEGORIES_FILTERS";

//Products types
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
